### ISSUE TITLE
Issues in LitmusChaos: Getting Started Tutorial

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/tutorials#15]
- [x] Full Stop missing in Welcome paragraph in page-1
- [x] Missing link for air-gapped environment setup in page-1
- [ ] Litmus installation link can be updated to the latest stable version in page-2
- [ ] Difference between cluster/namespace mode, and their installation steps in the docs should be referenced in page-2
- [x] Typo in "Verify Successful Registration of the Self Agent" paragraph in page-3, **automagically -> automatically**
- [x] In "Verify Successful Registration of the Self Agent" paragraph in page-3, change Portal to ChaosCenter
- [x] Typo in page-5, second paragraph, **onto -> on to**
- [x] Analytics section can be updated to Observability section in page-6, screenshots can also be updated for the same
- [ ] Done button on page-8 redirects to a link which causes a 404 error.

**Comment by Gbahdeyboh** [comment]
Hi @ksatchit.

Please kindly share a link to the Google Docs used in writing this tutorial, so I can edit and fix the issues highlighted in this issue.
