### ISSUE TITLE
Issues in Running Chaos Workflows on Remote Clusters Tutorial

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/tutorials#17]
- [ ] Update Litmus installation URL to the latest stable version on page 3
- [ ] In the step for exposing the NodePorts for GCP Firewall, the command for exposing the `litmusportal-server-service` NodePort is missing on page 3
- [ ] Download links for Litmusctl can be updated for the latest version
- [ ] There's a lack of clarity on which type of target cluster is being used. Assuming from the fact that the tutorial asks users to install Litmusctl on their own machines, a Minikube or k3s cluster is serving as the target cluster, in which the agent is getting installed. This should be properly elucidated.
- [ ] Upon the successful installation of the external agent, the agent components can also be manually checked from the target cluster using the CLI. This can be included to enhance the user's understanding of how the external agent is getting set-up. 
- [ ] Button names can be highlighted wherever necessary.
- [ ] Done button on page 8 redirects to a link which causes a 404 error.

**Comment by Gbahdeyboh** [comment]
`In the step for exposing the NodePorts for GCP Firewall, the command for exposing the litmusportal-server-service NodePort is missing on page 3`

The command id there, they're to fill in the pseudo code with the respective ports.

**Comment by Gbahdeyboh** [comment]
`Download links for Litmusctl can be updated for the latest version`

A note was added for the use of latest versions due to compatibility issues.

<img width="776" alt="Screenshot 2021-11-15 at 1 30 50 AM" src="https://user-images.githubusercontent.com/29985200/141705381-4d182a9d-ccce-48af-9d79-a9c652b13b5c.png">

**Comment by Gbahdeyboh** [comment]
`There's a lack of clarity on which type of target cluster is being used. Assuming from the fact that the tutorial asks users to install Litmusctl on their own machines, a Minikube or k3s cluster is serving as the target cluster, in which the agent is getting installed. This should be properly elucidated.`

I am not sure I understand this correctly.

**Comment by neelanjan00** [comment]
> The command id there, they're to fill in the pseudo code with the respective ports.

In my opinion, it will be better if we can abstract the same in two separate steps, one for `frontend-service-rule` and another for `server-service-rule`.

**Comment by neelanjan00** [comment]
> `Download links for Litmusctl can be updated for the latest version`
> 
> A note was added for the use of latest versions due to compatibility issues.
> 
> <img alt="Screenshot 2021-11-15 at 1 30 50 AM" width="776" src="https://user-images.githubusercontent.com/29985200/141705381-4d182a9d-ccce-48af-9d79-a9c652b13b5c.png">

What I meant is we have the download links for the different versions on page 4, but they are only till v0.3.0. We also have v0.4.0 and v0.5.0 available which we can add to the tutorial. You can check here: https://github.com/litmuschaos/litmusctl#installation

**Comment by neelanjan00** [comment]
> `There's a lack of clarity on which type of target cluster is being used. Assuming from the fact that the tutorial asks users to install Litmusctl on their own machines, a Minikube or k3s cluster is serving as the target cluster, in which the agent is getting installed. This should be properly elucidated.`
> 
> I am not sure I understand this correctly.

As per the tutorial, the Litmus Control Plane is set up in GKE, but there's no explicit information about where the target cluster is set up. On page 4, although we have mentioned that `kubeconfig` and `kubectl` are pre-requisites, it would be worth mentioning that they are corresponding to the target cluster and not the cluster in which the control plane is situated i.e. the GKE cluster.

**Comment by Gbahdeyboh** [comment]
All of this are now fixed @neelanjan00.

**Comment by neelanjan00** [comment]
LGTM @Gbahdeyboh

**Comment by neelanjan00** [comment]
Closing this issue as it has been fixed.
