### ISSUE TITLE
Issues in Observing Chaos Impact On Services Tutorial

### ISSUE THREAD

**Issue by neelanjan00** [litmuschaos/tutorials#19]
- [ ]  Analytics section can be updated to Observability. Screenshots can also be updated accordingly.
- [ ]  Done button on page 7 redirects to a link which causes a 404 error.

**Comment by Gbahdeyboh** [comment]
Hi, @neelanjan00.

Thanks a lot for the feedbacks.

The section reads "Analytics" on my Chaos Center. I have Litmus Beta8 installed, could this be the reason for the difference?

**Comment by neelanjan00** [comment]
> Hi, @neelanjan00.
> 
> Thanks a lot for the feedbacks.
> 
> The section reads "Analytics" on my Chaos Center. I have Litmus Beta8 installed, could this be the reason for the difference?

Yes, in the latest stable version, it has been renamed to Observability. You can install the latest version to check.

**Comment by neelanjan00** [comment]
Closing this issue as it has been fixed.
