### ISSUE TITLE
Broken Image for the following page

### ISSUE THREAD

**Issue by hrittikhere** [litmuschaos/tutorials#35]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/67012359/186493328-ca88cdda-1480-4fff-8ab5-9f9a69c939dc.png">

https://github.com/litmuschaos/tutorials/blob/74c7a6369c64cb58980fcdbb782b408f29eed982/tutorial-getting-started/index.html#L171

**Comment by Adarshkumar14** [comment]
PR: [https://github.com/litmuschaos/tutorials/pull/36](https://github.com/litmuschaos/tutorials/pull/36)
